name: Weekly Trivy Scan

on:
  schedule:
    - cron: '0 2 * * 0' # Run every Sunday at 2 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  re-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Latest Image
        run: docker pull andreibuakakaka/hawk-hello-world:latest

      - name: Scan Latest Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'andreibuakakaka/hawk-hello-world:latest'
          format: 'table'
          exit-code: '1' # Fail if vulnerabilities are found
          ignore-unfixed: true # Don't fail on vulnerabilities with no fix available
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' # Only fail on Critical or High severity
          # *** REMOVED PLACEHOLDER COMMENT *** 