name: Weekly Trivy Scan

on:
  schedule:
    - cron: '0 2 * * 0' # Run every Sunday at 2 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Latest Image
        run: docker pull ${{ github.repository_owner }}/hawk-hello-world:latest

      - name: Scan Latest Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ github.repository_owner }}/hawk-hello-world:latest'
          format: 'table'
          exit-code: '0' # Don't fail the workflow, just report
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
